#!/bin/sh
BASEDIR=$(dirname $0)
ruby -rubygems -I $BASEDIR/../lib $BASEDIR/../bin/twine $@ "generate-all-localization-files" "./test/input/strings.txt" "./test/output/ios/" "--format" "apple" "--tags" "ios" "--create-folders"
ruby -rubygems -I $BASEDIR/../lib $BASEDIR/../bin/twine $@ "generate-all-localization-files" "./test/input/strings.txt" "./test/output/android/" "--format" "android" "--tags" "android" "--create-folders"
ruby -rubygems -I $BASEDIR/../lib $BASEDIR/../bin/twine $@ "generate-all-localization-files" "./test/input/strings.txt" "./test/output/web/" "--format" "json" "--tags" "web" "--create-folders"
